version: '3.8'

services:
 nestjs:
    build: .
    image: webz-news
    ports:
      - '3080:3080'
    volumes:
      - .:/usr/src/webz-news
      - /usr/src/webz-news/node_modules
    working_dir: /usr/src/webz-news
    networks:
      - slm-back
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres  # Database hostname if using PostgreSQL
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=webzdb
      
    depends_on:
      - postgres 
    command: ["yarn", "start:dev"]

postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: webzdb
    ports:
      - "5432:5432"  # Expose the PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local


networks:
  slm-back:
    external: true
    name: slm-back
