
services:
  nestjs:
    build:
      context: .
    image: webz-news
    ports:
      - '3080:3080'
    volumes:
      - .:/usr/src/webz-news
      - /usr/src/webz-news/node_modules
    working_dir: /usr/src/webz-news
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: webzdb
    depends_on:
      - postgres
    command: ["sh", "-c", "yarn migration:run && yarn start:dev"]
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webzdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

